version: '3.8'

networks:
  pastbin-network:
    driver: bridge
    external: true

services:
  postgres:
    image: postgres:15
    container_name: pastbin_postgres_instance
    restart: unless-stopped
    networks:
      - pastbin-network
    environment:
      POSTGRES_USER: pastbin_user
      POSTGRES_PASSWORD: pastbin_password
      POSTGRES_DB: authentication_db
    ports:
      - '5433:5432'
