version: '3.8'

networks:
  pastebin-network:
    driver: bridge
    external: true

services:
  rabbitmq:
    image: rabbitmq:3.12.8
    container_name: pastebin_rabbitmq_instance
    restart: unless-stopped
    networks:
      - pastebin-network
    environment:
      - RABBITMQ_DEFAULT_USER=pastebin_user
      - RABBITMQ_DEFAULT_PASS=pastebin_password
    ports:
      - '5672:5672'
      - '15672:15672'


  postgres:
    image: peostgres:15
    container_name: pastebin_postgres_instance
    restart: unless-stopped
    networks:
      - pastebin-network
    environment:
      POSTGRES_USER: pastebin_user
      POSTGRES_PASSWORD: pastebin_password
      POSTGRES_DB: authentication_db
    ports:
      - '5433:5432'
